-- =========================================================
-- V1__create_initial_schema.sql
-- Initial EkoSrekja database schema
-- =========================================================


-- =========================================================
-- USERS
-- Must exist before V2 creates the admins table
-- =========================================================

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    account_non_expired     BOOLEAN,
    account_non_locked      BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled                 BOOLEAN,

    email                   VARCHAR(255) NOT NULL,
    username                VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,

    first_name              VARCHAR(255),
    last_name               VARCHAR(255),

    created_at              BIGINT,
    updated_at              BIGINT,

    is_admin                BOOLEAN,

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT uq_users_username
        UNIQUE (username)
);


-- =========================================================
-- HOROSCOPE
-- created_at is intentionally omitted because V4 adds it
-- =========================================================

CREATE TABLE horoscope_entries
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    sign        VARCHAR(255) NOT NULL,
    period_type VARCHAR(255) NOT NULL,
    period_date DATE         NOT NULL,

    title       VARCHAR(255),
    content     VARCHAR(4000),
    eco_tip     VARCHAR(255),

    CONSTRAINT uq_horoscope
        UNIQUE (sign, period_type, period_date)
);

CREATE INDEX idx_horoscope_period
    ON horoscope_entries (period_type, period_date);


-- =========================================================
-- GAMES
-- =========================================================

CREATE TABLE games
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    title         VARCHAR(255) NOT NULL,
    description   VARCHAR(3000),
    rules         VARCHAR(4000),
    difficulty    VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255)
);

CREATE INDEX idx_games_difficulty
    ON games (difficulty);


-- =========================================================
-- NEWS
-- =========================================================

CREATE TABLE news
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    title        VARCHAR(255)  NOT NULL,
    content      VARCHAR(8000) NOT NULL,
    category     VARCHAR(255),
    cover_url    VARCHAR(255),

    published_at TIMESTAMP,
    published    BOOLEAN DEFAULT FALSE,

    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE
);


-- =========================================================
-- PHOTOS
-- =========================================================

CREATE TABLE photos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    title         VARCHAR(255) NOT NULL,
    description   VARCHAR(2000),

    url           VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255),
    tags          VARCHAR(255),

    created_at    TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_photos_created_at
    ON photos (created_at);


-- =========================================================
-- QUIZZES
-- Parent table must be created before quiz questions
-- =========================================================

CREATE TABLE quiz
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    title           VARCHAR(255) NOT NULL,
    level           VARCHAR(255) NOT NULL,
    description     TEXT,

    time_minutes    INTEGER DEFAULT 5,
    active          BOOLEAN DEFAULT TRUE,
    cover_image_url TEXT,

    CONSTRAINT chk_quiz_time_minutes
        CHECK (time_minutes IS NULL OR time_minutes > 0)
);


-- =========================================================
-- QUIZ QUESTIONS
-- Must exist before quiz_option
-- =========================================================

CREATE TABLE quiz_question
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    quiz_id BIGINT NOT NULL,
    text    TEXT   NOT NULL,

    CONSTRAINT fk_quiz_question_quiz
        FOREIGN KEY (quiz_id)
            REFERENCES quiz (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_quiz_question_quiz_id
    ON quiz_question (quiz_id);


-- =========================================================
-- QUIZ OPTIONS
-- =========================================================

CREATE TABLE quiz_option
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    question_id BIGINT  NOT NULL,
    text        TEXT    NOT NULL,
    is_correct  BOOLEAN DEFAULT FALSE NOT NULL,
    ord         INTEGER DEFAULT 0     NOT NULL,

    CONSTRAINT fk_quiz_option_question
        FOREIGN KEY (question_id)
            REFERENCES quiz_question (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_quiz_option_order
        CHECK (ord >= 0)
);

CREATE INDEX idx_quiz_option_question_id
    ON quiz_option (question_id);


-- =========================================================
-- QUIZ SUBMISSIONS
-- =========================================================

CREATE TABLE quiz_submission
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    quiz_id    BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    score      INTEGER NOT NULL,
    total      INTEGER NOT NULL,

    CONSTRAINT fk_quiz_submission_quiz
        FOREIGN KEY (quiz_id)
            REFERENCES quiz (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_quiz_submission_score
        CHECK (score >= 0),

    CONSTRAINT chk_quiz_submission_total
        CHECK (total >= 0),

    CONSTRAINT chk_quiz_submission_score_total
        CHECK (score <= total)
);

CREATE INDEX idx_quiz_submission_quiz_id
    ON quiz_submission (quiz_id);


-- =========================================================
-- VIDEOS
-- =========================================================

CREATE TABLE videos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(2000),

    source       VARCHAR(255) NOT NULL,
    ref          VARCHAR(255) NOT NULL,

    duration_sec INTEGER,

    created_at   TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT chk_videos_duration
        CHECK (duration_sec IS NULL OR duration_sec >= 0)
);

CREATE INDEX idx_videos_created_at
    ON videos (created_at);