CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    enabled BOOLEAN,
    account_non_expired BOOLEAN,
    account_non_locked BOOLEAN,
    credentials_non_expired BOOLEAN,
    is_admin BOOLEAN,
    created_at BIGINT,
    updated_at BIGINT
);

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    role_name VARCHAR(255) NOT NULL DEFAULT 'ADMIN',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users(id)
);

WITH admin_user AS (
    INSERT INTO users (
        username,
        email,
        password,
        first_name,
        last_name,
        enabled,
        account_non_expired,
        account_non_locked,
        credentials_non_expired,
        is_admin,
        created_at,
        updated_at
    )
    VALUES (
        'admin_test',
        'admin@test.local',
        '$2a$10$QFjj0lE3mWcVORfQZ0K/J.IeSfiHrq7N9H8ROxap9pp5lJ8NKRaI.',
        'Admin',
        'Tester',
        TRUE,
        TRUE,
        TRUE,
        TRUE,
        TRUE,
        FLOOR(EXTRACT(EPOCH FROM NOW()) * 1000),
        FLOOR(EXTRACT(EPOCH FROM NOW()) * 1000)
    )
    ON CONFLICT (username) DO UPDATE SET
        email = EXCLUDED.email,
        password = EXCLUDED.password,
        first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        enabled = TRUE,
        account_non_expired = TRUE,
        account_non_locked = TRUE,
        credentials_non_expired = TRUE,
        is_admin = TRUE,
        updated_at = FLOOR(EXTRACT(EPOCH FROM NOW()) * 1000)
    RETURNING id
)
INSERT INTO admins (user_id, role_name, created_at)
SELECT id, 'ADMIN', NOW()
FROM admin_user
ON CONFLICT (user_id) DO UPDATE SET role_name = EXCLUDED.role_name;
